name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore PlatformService.csproj
    - name: Build
      run: dotnet build PlatformService.csproj --no-restore
    - name: Test
      run: dotnet test PlatformService.csproj --no-build --verbosity normal
